# Generated by Django 4.2.5 on 2023-12-06 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('images', models.TextField(null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('social', models.TextField()),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='categories.category')),
            ],
        ),
    ]
