# Generated by Django 4.2.5 on 2023-12-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='images',
            field=models.TextField(null=True),
        ),
    ]
