# Generated by Django 4.2.5 on 2024-01-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_description_alter_service_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
