# Generated by Django 4.2.5 on 2023-09-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NORMAL'), (2, 'PROVIDER'), (3, 'ADMIN')]),
        ),
    ]
